
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep 29 2026 11:43:30 EDT (Sep 29 2026 15:43:30 UTC)

// Verification Directory fv/alu_4bit 

module alu_4bit(clk, rst_n, a_in, b_in, opcode_in, alu_out, carry_out,
     zero_flag);
  input clk, rst_n;
  input [3:0] a_in, b_in;
  input [2:0] opcode_in;
  output [3:0] alu_out;
  output carry_out, zero_flag;
  wire clk, rst_n;
  wire [3:0] a_in, b_in;
  wire [2:0] opcode_in;
  wire [3:0] alu_out;
  wire carry_out, zero_flag;
  wire [2:0] opcode_reg;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57;
  DFFRHQX4 zero_flag_reg(.RN (rst_n), .CK (clk), .D (n_57), .Q
       (zero_flag));
  NOR4BBX1 g1766__2398(.AN (n_34), .BN (n_54), .C (n_53), .D (n_56), .Y
       (n_57));
  DFFRHQX4 \alu_out_reg[3] (.RN (rst_n), .CK (clk), .D (n_55), .Q
       (alu_out[3]));
  DFFRHQX4 \alu_out_reg[2] (.RN (rst_n), .CK (clk), .D (n_56), .Q
       (alu_out[2]));
  INVXL g1770(.A (n_54), .Y (n_55));
  AOI22X1 g1772__5107(.A0 (n_49), .A1 (n_51), .B0 (n_10), .B1 (n_28),
       .Y (n_54));
  DFFRHQX4 carry_out_reg(.RN (rst_n), .CK (clk), .D (n_52), .Q
       (carry_out));
  OAI211X1 g1771__6260(.A0 (n_2), .A1 (n_48), .B0 (n_24), .C0 (n_50),
       .Y (n_56));
  DFFRHQX4 \alu_out_reg[1] (.RN (rst_n), .CK (clk), .D (n_53), .Q
       (alu_out[1]));
  OAI31X1 g1773__4319(.A0 (opcode_reg[1]), .A1 (opcode_reg[2]), .A2
       (n_45), .B0 (n_25), .Y (n_52));
  XNOR2X1 g1775__8428(.A (a_reg[3]), .B (n_47), .Y (n_51));
  AOI22X1 g1776__5526(.A0 (n_49), .A1 (n_46), .B0 (a_reg[3]), .B1
       (n_43), .Y (n_50));
  OAI211X1 g1777__6783(.A0 (n_4), .A1 (n_48), .B0 (n_22), .C0 (n_44),
       .Y (n_53));
  OAI22X1 g1780__3680(.A0 (opcode_reg[2]), .A1 (n_41), .B0 (b_reg[3]),
       .B1 (n_37), .Y (n_47));
  XNOR2X1 g1778__1617(.A (a_reg[2]), .B (n_38), .Y (n_46));
  XNOR2X1 g1779__2802(.A (opcode_reg[0]), .B (n_42), .Y (n_45));
  AOI22X1 g1781__1705(.A0 (n_49), .A1 (n_36), .B0 (a_reg[2]), .B1
       (n_43), .Y (n_44));
  OAI22X1 g1782__5122(.A0 (n_17), .A1 (n_39), .B0 (n_16), .B1 (n_40),
       .Y (n_42));
  XOR2XL g1783__8246(.A (n_40), .B (n_39), .Y (n_41));
  OAI22X1 g1784__7098(.A0 (opcode_reg[2]), .A1 (n_31), .B0 (b_reg[2]),
       .B1 (n_37), .Y (n_38));
  DFFRHQX4 \alu_out_reg[0] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (alu_out[0]));
  OAI31X1 g1785__6131(.A0 (b_reg[1]), .A1 (n_32), .A2 (n_37), .B0
       (n_33), .Y (n_36));
  INVXL g1791(.A (n_34), .Y (n_35));
  AOI22X1 g1786__1881(.A0 (n_1), .A1 (n_29), .B0 (n_32), .B1 (n_9), .Y
       (n_33));
  XNOR2X1 g1787__5115(.A (n_13), .B (n_30), .Y (n_31));
  AOI22X1 g1788__7482(.A0 (n_14), .A1 (n_30), .B0 (a_reg[2]), .B1
       (n_11), .Y (n_39));
  AOI221X1 g1792__4733(.A0 (b_reg[0]), .A1 (n_15), .B0 (a_reg[0]), .B1
       (n_26), .C0 (n_27), .Y (n_34));
  ADDFX1 g1790__6161(.A (n_5), .B (a_reg[1]), .CI (n_8), .CO (n_30), .S
       (n_29));
  OAI221X1 g1793__9315(.A0 (n_49), .A1 (n_3), .B0 (n_6), .B1 (n_48),
       .C0 (n_18), .Y (n_28));
  OAI2BB1X1 g1795__9945(.A0N (a_reg[1]), .A1N (n_43), .B0 (n_20), .Y
       (n_27));
  OAI211X1 g1794__2883(.A0 (opcode_reg[1]), .A1 (n_19), .B0 (n_48), .C0
       (n_12), .Y (n_26));
  AOI22X1 g1799__2346(.A0 (a_reg[3]), .A1 (n_23), .B0 (a_reg[0]), .B1
       (n_43), .Y (n_25));
  AOI32X1 g1800__1666(.A0 (a_reg[2]), .A1 (b_reg[2]), .A2 (n_21), .B0
       (a_reg[1]), .B1 (n_23), .Y (n_24));
  AOI32X1 g1801__7410(.A0 (a_reg[1]), .A1 (b_reg[1]), .A2 (n_21), .B0
       (a_reg[0]), .B1 (n_23), .Y (n_22));
  NAND3BXL g1798__6417(.AN (a_reg[0]), .B (n_49), .C (n_19), .Y (n_20));
  OAI211X1 g1796__5477(.A0 (b_reg[3]), .A1 (opcode_reg[0]), .B0
       (a_reg[3]), .C0 (n_21), .Y (n_18));
  AND2XL g1797__2398(.A (n_16), .B (n_40), .Y (n_17));
  INVXL g1803(.A (n_48), .Y (n_15));
  NAND2X1 g1802__5107(.A (n_0), .B (n_13), .Y (n_14));
  NAND2XL g1804__6260(.A (b_reg[0]), .B (n_21), .Y (n_12));
  NOR2X1 g1806__4319(.A (n_49), .B (n_37), .Y (n_23));
  NAND2X1 g1808__8428(.A (opcode_reg[0]), .B (n_21), .Y (n_48));
  INVXL g1809(.A (n_13), .Y (n_11));
  NAND2BXL g1805__5526(.AN (b_reg[0]), .B (n_10), .Y (n_19));
  NOR2X1 g1807__6783(.A (n_49), .B (n_10), .Y (n_43));
  OAI2BB1X1 g1810__3680(.A0N (opcode_reg[2]), .A1N (b_reg[1]), .B0
       (n_10), .Y (n_9));
  MXI2XL g1811__1617(.A (n_7), .B (opcode_reg[0]), .S0 (b_reg[1]), .Y
       (n_8));
  AOI22X1 g1813__2802(.A0 (b_reg[3]), .A1 (n_7), .B0 (n_6), .B1
       (opcode_reg[0]), .Y (n_40));
  NAND2X1 g1819__1705(.A (opcode_reg[2]), .B (n_7), .Y (n_37));
  NOR2X1 g1820__5122(.A (opcode_reg[2]), .B (n_49), .Y (n_21));
  MX2XL g1814__8246(.A (opcode_reg[0]), .B (a_reg[0]), .S0 (b_reg[0]),
       .Y (n_5));
  XNOR2X1 g1812__7098(.A (b_reg[2]), .B (opcode_reg[0]), .Y (n_13));
  NOR2XL g1816__6131(.A (a_reg[1]), .B (b_reg[1]), .Y (n_4));
  NAND2XL g1817__1881(.A (a_reg[2]), .B (opcode_reg[2]), .Y (n_3));
  NOR2XL g1815__5115(.A (a_reg[2]), .B (b_reg[2]), .Y (n_2));
  NAND2X1 g1818__7482(.A (opcode_reg[2]), .B (opcode_reg[0]), .Y
       (n_10));
  DFFRHQX1 \b_reg_reg[0] (.RN (rst_n), .CK (clk), .D (b_in[0]), .Q
       (b_reg[0]));
  DFFRHQX1 \b_reg_reg[1] (.RN (rst_n), .CK (clk), .D (b_in[1]), .Q
       (b_reg[1]));
  DFFRHQX1 \a_reg_reg[0] (.RN (rst_n), .CK (clk), .D (a_in[0]), .Q
       (a_reg[0]));
  DFFRHQX1 \b_reg_reg[2] (.RN (rst_n), .CK (clk), .D (b_in[2]), .Q
       (b_reg[2]));
  DFFRX1 \opcode_reg_reg[2] (.RN (rst_n), .CK (clk), .D (opcode_in[2]),
       .Q (opcode_reg[2]), .QN (n_1));
  DFFRX1 \b_reg_reg[3] (.RN (rst_n), .CK (clk), .D (b_in[3]), .Q
       (b_reg[3]), .QN (n_6));
  DFFRX1 \a_reg_reg[3] (.RN (rst_n), .CK (clk), .D (a_in[3]), .Q
       (a_reg[3]), .QN (n_16));
  DFFRX1 \a_reg_reg[2] (.RN (rst_n), .CK (clk), .D (a_in[2]), .Q
       (a_reg[2]), .QN (n_0));
  DFFRX1 \a_reg_reg[1] (.RN (rst_n), .CK (clk), .D (a_in[1]), .Q
       (a_reg[1]), .QN (n_32));
  DFFRX1 \opcode_reg_reg[0] (.RN (rst_n), .CK (clk), .D (opcode_in[0]),
       .Q (opcode_reg[0]), .QN (n_7));
  DFFRX1 \opcode_reg_reg[1] (.RN (rst_n), .CK (clk), .D (opcode_in[1]),
       .Q (opcode_reg[1]), .QN (n_49));
endmodule

